name: 'spec_test_table'
number_of_records: 3
size_of_bulk: 2
columns:
  - name: name
    data_type: string
    value_type: random
    length: 5
  - name: age
    data_type: number
    value_type: random
    range: [5, 10]
  - name: rank
    data_type: number
    value_type: sequential
    start: 2
    increment: 5
  - name: join_date
    data_type: date
    value_type: sequential
    start: '2021-04-30'
    day_increment: 5
