name: 'example_table'
number_of_records: 10
size_of_bulk: 4
columns:
- name: name
  data_type: string
  value_type: random
  length: 5
- name: age
  data_type: number
  value_type: random
  range: [5, 10]
- name: rank
  data_type: number
  value_type: sequential
  start: 2
  increment: 5
