name: 'sample'
number_of_records: 1000000
size_of_bulk: 10000
columns:
  - name: name
    data_type: string
    value_type: random
    length: 5
  - name: age
    data_type: number
    value_type: random
    range: [5, 90]
  - name: rank
    data_type: number
    value_type: sequential
    start: 2
    increment: 2
  - name: join_date
    data_type: date
    value_type: sequential
    start: '2021-04-30'
    day_increment: 3
